### ISSUE TITLE
Setup ESLint

### ISSUE THREAD

**Issue by imbsky** [arrowresearch/vscode-merlin#3]

**Comment by imbsky** [comment]
To avoid conflicts, I will check if #2 is merged or closed before I proceed with this.

**Comment by andreypopp** [comment]
Considering we use typescript here, should we use tslint?

**Comment by imbsky** [comment]
> TSLint will be deprecated some time in 2019.

and TypeScript ESLint is currently very stable!
https://github.com/typescript-eslint/typescript-eslint

**Comment by prometheansacrifice** [comment]
@imbsky We just migrated the extension to Reason. Thanks for taking this up, nevertheless. Appreciate the initiative :)
