### ISSUE TITLE
Setup Rollup

### ISSUE THREAD

**Issue by imbsky** [arrowresearch/vscode-merlin#5]

**Comment by imbsky** [comment]
By doing only type checking with the TypeScript Compiler, we have more flexibility in managing our build artifacts.

**Comment by andreypopp** [comment]
Can elaborate why we need a bundler for vscode extension (I thought we could ship everything as separate modules)?

**Comment by andreypopp** [comment]
Can you elaborate why we need a bundler for vscode extension (I thought we could ship everything as separate modules)?

**Comment by imbsky** [comment]
TypeScript compiler sometimes bundles modules that are too large. So I think it would be cleaner to use Babel to delete only TypeScript type definitions and transpile to a specified ECMAScript version.

**Comment by prometheansacrifice** [comment]
Closed by #22
